language: node_js
node_js: stable
cache:
    apt: true
    directories:
        - node_modules
sudo: required
git:
    quiet: true
install:
    - sudo apt-get install -y sshpass
script:
    - npm install nodemailer
    - pwd
    - ls -a
    - echo "running mail.js"
    - node .gitemail.js "li@latelee.org, latelee@163.com" "自动化CI测试" https://github.com/latelee/testci

after_script:
    - echo "after script"
    - export SSHPASS=${hostkey}
    - sshpass -e ssh ${hostman}@${hostname} -o StrictHostKeyChecking=no "date > /tmp/foo"
    - echo $?
env:
    global:
        - AUTHOR: latelee