language: node_js
node_js: stable
cache:
    apt: true
    directories:
        - node_modules
script:
    - npm install
    - pwd
    - ls -a
    - echo "running mail.js"
    - node mail.js "li@latelee.org, latelee@163.com" "自动化CI测试" https://github.com/latelee/testci